/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_bringardner_io_filesource_viewer_registry_MacLaunchService */

#ifndef _IncludeGetLaunchData
#define _IncludeGetLaunchData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_bringardner_io_filesource_viewer_registry_MacLaunchService
 * Method:    getLaunchData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_us_bringardner_io_filesource_viewer_registry_MacRegistry_getLaunchData(JNIEnv *env, jobject obj, jstring string);

#ifdef __cplusplus
}
#endif
#endif
